### ISSUE TITLE
MongoDB database URL is exposed.

### ISSUE THREAD

**Issue by zippytyro** [rt1301/Shopify#2]
Hi, @rt1301 your database URL is exposed in **app.js** which can be abused.
Make sure you use dotenv package from NPM to save these config URLs there.

Also would love to see the hosted project somewhere.

**Comment by rt1301** [comment]
@zippytyro  Thanks for mentioning this, it was actually a private Project before hence the url was exposed. As far as deployment is concerned there are a few changes that have to made to this application for to be production ready 😅

**Comment by rt1301** [comment]
this issue is fixed, so I am closing it now
